import smtplib
import html
import re

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import EMAIL_ADDRESS, EMAIL_PASSWORD

from database import get_users_for_alert

from severity_filter import allow_alert


# ==========================================================
# CONFIGURATION
# ==========================================================

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

DEFAULT_DASHBOARD_URL = "http://192.168.1.13:5000"


# ==========================================================
# CLEAN SUMMARY FOR EMAIL
# ==========================================================

def clean_summary(summary):
    """
    Convert the Markdown summary generated by the AI
    into simple HTML suitable for email.
    """

    if not summary:
        return "<p>No summary available.</p>"


    summary = str(summary)

    # Escape HTML characters first
    summary = html.escape(summary)


    # Convert Markdown headings

    summary = re.sub(
        r"##\s*\*\*(.*?)\*\*",
        r"<h4>\1</h4>",
        summary
    )


    # Convert bold Markdown

    summary = re.sub(
        r"\*\*(.*?)\*\*",
        r"<strong>\1</strong>",
        summary
    )


    # Process lines

    lines = summary.split("\n")

    output = []

    in_list = False


    for line in lines:

        line = line.strip()


        # --------------------------------------------------
        # Bullet point
        # --------------------------------------------------

        if line.startswith("- "):

            if not in_list:

                output.append("<ul>")

                in_list = True


            output.append(
                f"<li>{line[2:]}</li>"
            )


        else:

            if in_list:

                output.append(
                    "</ul>"
                )

                in_list = False


            if line:

                # Don't wrap HTML headings in <p>
                if (
                    line.startswith("<h4>")
                    and line.endswith("</h4>")
                ):

                    output.append(
                        line
                    )

                else:

                    output.append(
                        f"<p>{line}</p>"
                    )


    if in_list:

        output.append(
            "</ul>"
        )


    return "\n".join(output)


# ==========================================================
# GET ARTICLE CVES
# ==========================================================

def get_article_cves(article):
    """
    Get CVE identifiers from the article dictionary.

    Supported fields:
        cves
        cve_ids
        cve

    CVE information can be:
        - list of strings
        - a single string
        - list of dictionaries
    """

    cves = []


    # ------------------------------------------------------
    # Preferred field
    # ------------------------------------------------------

    if article.get("cves"):

        cves = article["cves"]


    # ------------------------------------------------------
    # Alternative field
    # ------------------------------------------------------

    elif article.get("cve_ids"):

        cves = article["cve_ids"]


    # ------------------------------------------------------
    # Single CVE field
    # ------------------------------------------------------

    elif article.get("cve"):

        cves = article["cve"]


    # ------------------------------------------------------
    # Convert single string to list
    # ------------------------------------------------------

    if isinstance(cves, str):

        cves = [cves]


    # ------------------------------------------------------
    # Ensure list
    # ------------------------------------------------------

    if not isinstance(cves, list):

        cves = [cves]


    return cves


# ==========================================================
# FORMAT CVE INFORMATION
# ==========================================================

def format_cves(article):
    """
    Create HTML for CVE information.
    """

    cves = get_article_cves(
        article
    )


    if not cves:

        return """
        <div
            style="
                background:#f8f9fa;
                border:1px solid #dee2e6;
                padding:12px;
                border-radius:5px;
            "
        >

            <em>No CVE detected.</em>

        </div>
        """


    cve_html = """

    <div
        style="
            background:#f8f9fa;
            border:1px solid #dee2e6;
            padding:12px;
            border-radius:5px;
        "
    >

    <ul
        style="
            margin:0;
            padding-left:20px;
        "
    >

    """


    for cve in cves:

        # --------------------------------------------------
        # CVE stored as dictionary
        # --------------------------------------------------

        if isinstance(
            cve,
            dict
        ):

            cve_id = cve.get(
                "cve_id",
                cve.get(
                    "id",
                    "Unknown CVE"
                )
            )


            cvss = cve.get(
                "cvss_score"
            )


            cve_severity = cve.get(
                "severity"
            )


            description = cve.get(
                "description"
            )


        # --------------------------------------------------
        # CVE stored as string
        # --------------------------------------------------

        else:

            cve_id = cve

            cvss = None

            cve_severity = None

            description = None


        cve_html += (
            "<li style='margin-bottom:8px;'>"
            "<strong>"
            + html.escape(
                str(cve_id)
            )
            + "</strong>"
        )


        if cvss:

            cve_html += (
                f"<br>"
                f"<small>"
                f"CVSS Score: "
                f"{html.escape(str(cvss))}"
                f"</small>"
            )


        if cve_severity:

            cve_html += (
                f"<br>"
                f"<small>"
                f"CVE Severity: "
                f"{html.escape(str(cve_severity))}"
                f"</small>"
            )


        if description:

            cve_html += (
                f"<br>"
                f"<small>"
                f"{html.escape(str(description))}"
                f"</small>"
            )


        cve_html += "</li>"


    cve_html += """

    </ul>

    </div>

    """


    return cve_html


# ==========================================================
# GET RECOMMENDATION
# ==========================================================

def get_article_recommendation(article):
    """
    Get the protection recommendation already generated
    for the article.

    A fallback recommendation is used if the article does
    not contain one.
    """

    recommendation = article.get(
        "recommendation"
    )


    if not recommendation:

        recommendation = (
            "Review the affected systems, "
            "apply available security updates, "
            "monitor for suspicious activity, "
            "review access controls, and follow "
            "appropriate cybersecurity best practices."
        )


    return recommendation


# ==========================================================
# SEVERITY STYLE
# ==========================================================

def get_severity_style(severity):

    severity = str(
        severity
    ).lower()


    if severity == "critical":

        return (
            "color:#dc3545;"
            "font-weight:bold;"
        )


    elif severity == "high":

        return (
            "color:#fd7e14;"
            "font-weight:bold;"
        )


    elif severity == "medium":

        return (
            "color:#b8860b;"
            "font-weight:bold;"
        )


    else:

        return (
            "color:#198754;"
            "font-weight:bold;"
        )


# ==========================================================
# SEND SECURITY EMAIL
# ==========================================================

def send_email(
    articles,
    alert_type="daily",
    subject=None,
    dashboard_url=DEFAULT_DASHBOARD_URL
):

    """
    Send personalised Security Digest emails.

    Supported alert types:

        daily
        weekly
        critical
    """


    # ======================================================
    # VALIDATE ARTICLES
    # ======================================================

    if not articles:

        print(
            f"[{alert_type}] No articles to send."
        )

        return False


    # ======================================================
    # GET SUBSCRIBED USERS
    # ======================================================

    try:

        users = get_users_for_alert(
            alert_type
        )

    except Exception as e:

        print(
            f"[{alert_type}] "
            f"Failed to get subscribers: {e}"
        )

        return False


    if not users:

        print(
            f"[{alert_type}] "
            f"No subscribers found."
        )

        return False


    # ======================================================
    # FILTER CRITICAL ARTICLES
    # ======================================================

    if alert_type == "critical":

        filtered_articles = [

            article

            for article in articles

            if str(
                article.get(
                    "severity",
                    "Low"
                )
            ).lower() == "critical"

        ]


    else:

        filtered_articles = list(
            articles
        )


    if not filtered_articles:

        print(
            f"[{alert_type}] "
            f"No matching articles."
        )

        return False


    # ======================================================
    # EMAIL SUBJECT
    # ======================================================

    if not subject:

        if alert_type == "critical":

            subject = (
                "🚨 Critical Security Alert - "
                "Security Digest"
            )


        elif alert_type == "weekly":

            subject = (
                "📅 Weekly Security Digest"
            )


        else:

            subject = (
                "📰 Daily Security Digest"
            )


    # ======================================================
    # CONNECT TO GMAIL
    # ======================================================

    try:

        with smtplib.SMTP(
            SMTP_SERVER,
            SMTP_PORT
        ) as smtp:


            # ------------------------------------------------
            # Start TLS
            # ------------------------------------------------

            smtp.starttls()


            # ------------------------------------------------
            # Login
            # ------------------------------------------------

            smtp.login(
                EMAIL_ADDRESS,
                EMAIL_PASSWORD
            )


            print(
                "Connected to Gmail SMTP successfully."
            )


            # ==================================================
            # SEND TO EACH USER
            # ==================================================

            for user in users:

                # IMPORTANT:
                # sqlite3.Row does not support .get()
                # Convert it to a normal dictionary.

                user = dict(
                    user
                )


                email = user.get(
                    "email"
                )


                if not email:

                    continue


                threshold = user.get(
                    "minimum_severity",
                    "Low"
                )


                # ----------------------------------------------
                # User-specific filtering
                # ----------------------------------------------

                user_articles = []


                for article in filtered_articles:

                    severity = article.get(
                        "severity",
                        "Low"
                    )


                    if allow_alert(
                        severity,
                        threshold
                    ):

                        user_articles.append(
                            article
                        )


                # ------------------------------------------------
                # No matching articles
                # ------------------------------------------------

                if not user_articles:

                    print(
                        f"No matching articles "
                        f"for {email}"
                    )

                    continue


                # ==================================================
                # EMAIL HEADER
                # ==================================================

                html_body = """

                <!DOCTYPE html>

                <html>

                <head>

                <meta charset="UTF-8">

                </head>


                <body
                    style="
                        margin:0;
                        padding:20px;
                        background:#f5f7fa;
                        font-family:Arial,
                        Helvetica,sans-serif;
                        color:#212529;
                    "
                >


                <div
                    style="
                        max-width:700px;
                        margin:0 auto;
                        background:#ffffff;
                        padding:30px;
                        border-radius:10px;
                        box-shadow:
                        0 2px 8px
                        rgba(0,0,0,0.08);
                    "
                >


                <h2
                    style="
                        margin-top:0;
                        color:#212529;
                    "
                >

                    🛡️ Security Digest

                </h2>


                <p
                    style="
                        color:#6c757d;
                    "
                >

                    Cybersecurity intelligence,
                    threat information and
                    recommended protection actions.

                </p>

                """


                # ==================================================
                # ARTICLES
                # ==================================================

                for article in user_articles:

                    # ----------------------------------------------
                    # Title
                    # ----------------------------------------------

                    title = html.escape(
                        str(
                            article.get(
                                "title",
                                "Untitled Article"
                            )
                        )
                    )


                    # ----------------------------------------------
                    # Severity
                    # ----------------------------------------------

                    severity = html.escape(
                        str(
                            article.get(
                                "severity",
                                "Low"
                            )
                        )
                    )


                    severity_style = (
                        get_severity_style(
                            severity
                        )
                    )


                    # ----------------------------------------------
                    # Category
                    # ----------------------------------------------

                    category = html.escape(
                        str(
                            article.get(
                                "category",
                                "General Security"
                            )
                        )
                    )


                    # ----------------------------------------------
                    # Source
                    # ----------------------------------------------

                    source = html.escape(
                        str(
                            article.get(
                                "source",
                                "Unknown"
                            )
                        )
                    )


                    # ----------------------------------------------
                    # Published date
                    # ----------------------------------------------

                    published_date = html.escape(
                        str(
                            article.get(
                                "published_date",
                                "N/A"
                            )
                        )
                    )


                    # ----------------------------------------------
                    # Original article URL
                    # ----------------------------------------------

                    url = article.get(
                        "link",
                        article.get(
                            "url",
                            "#"
                        )
                    )


                    url = html.escape(
                        str(url),
                        quote=True
                    )


                    # ----------------------------------------------
                    # Summary
                    # ----------------------------------------------

                    summary = clean_summary(
                        article.get(
                            "summary",
                            ""
                        )
                    )


                    # ----------------------------------------------
                    # CVE
                    # ----------------------------------------------

                    cve_html = format_cves(
                        article
                    )


                    # ----------------------------------------------
                    # Recommendation
                    # ----------------------------------------------

                    recommendation = (
                        get_article_recommendation(
                            article
                        )
                    )


                    recommendation = html.escape(
                        str(
                            recommendation
                        )
                    )


                    # ==================================================
                    # ARTICLE CARD
                    # ==================================================

                    html_body += f"""

                    <div
                        style="
                            margin-top:25px;
                            padding:20px;
                            border:1px solid #dee2e6;
                            border-radius:8px;
                            background:#ffffff;
                        "
                    >


                    <!-- TITLE -->

                    <h3
                        style="
                            margin-top:0;
                            margin-bottom:15px;
                            color:#212529;
                        "
                    >

                        {title}

                    </h3>


                    <!-- SEVERITY -->

                    <p>

                        <strong>
                            Severity:
                        </strong>

                        <span
                            style="{severity_style}"
                        >

                            {severity}

                        </span>

                    </p>


                    <!-- CATEGORY -->

                    <p>

                        <strong>
                            Category:
                        </strong>

                        {category}

                    </p>


                    <!-- SOURCE -->

                    <p>

                        <strong>
                            Source:
                        </strong>

                        {source}

                    </p>


                    <!-- PUBLISHED DATE -->

                    <p>

                        <strong>
                            Published:
                        </strong>

                        {published_date}

                    </p>


                    <!-- SUMMARY -->

                    <h4
                        style="
                            margin-top:20px;
                            border-bottom:
                            1px solid #dee2e6;
                            padding-bottom:6px;
                        "
                    >

                        Summary

                    </h4>


                    <div>

                        {summary}

                    </div>


                    <!-- CVE INFORMATION -->

                    <h4
                        style="
                            margin-top:20px;
                            border-bottom:
                            1px solid #dee2e6;
                            padding-bottom:6px;
                        "
                    >

                        CVE Information

                    </h4>


                    <div>

                        {cve_html}

                    </div>


                    <!-- PROTECTION RECOMMENDATION -->

                    <h4
                        style="
                            margin-top:20px;
                            border-bottom:
                            1px solid #dee2e6;
                            padding-bottom:6px;
                        "
                    >

                        Protection Recommendation

                    </h4>


                    <div
                        style="
                            background:#f1f3f5;
                            border-left:
                            5px solid #0d6efd;
                            padding:15px;
                            border-radius:5px;
                            line-height:1.6;
                        "
                    >

                        {recommendation}

                    </div>


                    <!-- READ ORIGINAL ARTICLE -->

                    <p
                        style="
                            margin-top:20px;
                        "
                    >

                        <a
                            href="{url}"
                            target="_blank"
                            style="
                                display:inline-block;
                                background:#0d6efd;
                                color:#ffffff;
                                padding:10px 16px;
                                text-decoration:none;
                                border-radius:5px;
                            "
                        >

                            Read Original Article ↗

                        </a>

                    </p>


                    </div>

                    """


                # ==================================================
                # OPEN DASHBOARD
                # ==================================================

                dashboard_url_safe = html.escape(
                    str(
                        dashboard_url
                    ),
                    quote=True
                )


                html_body += f"""

                <!-- DASHBOARD -->

                <div
                    style="
                        margin-top:30px;
                        padding-top:20px;
                        border-top:
                        1px solid #dee2e6;
                        text-align:center;
                    "
                >

                    <a
                        href="{dashboard_url_safe}"
                        target="_blank"
                        style="
                            display:inline-block;
                            background:#212529;
                            color:#ffffff;
                            padding:11px 20px;
                            text-decoration:none;
                            border-radius:5px;
                        "
                    >

                        Open Security Dashboard

                    </a>

                </div>


                <!-- FOOTER -->

                <p
                    style="
                        margin-top:30px;
                        color:#6c757d;
                        font-size:12px;
                        text-align:center;
                    "
                >

                    This email was generated
                    automatically by the
                    Security Digest System.

                </p>


                </div>

                </body>

                </html>

                """


                # ==================================================
                # CREATE EMAIL MESSAGE
                # ==================================================

                msg = MIMEMultipart(
                    "alternative"
                )


                msg["Subject"] = subject

                msg["From"] = EMAIL_ADDRESS

                msg["To"] = email


                # Attach HTML email

                msg.attach(
                    MIMEText(
                        html_body,
                        "html",
                        "utf-8"
                    )
                )


                # ==================================================
                # SEND EMAIL
                # ==================================================

                smtp.send_message(
                    msg
                )


                print(
                    f"Email sent -> {email}"
                )


    # ==========================================================
    # GMAIL AUTHENTICATION ERROR
    # ==========================================================

    except smtplib.SMTPAuthenticationError:

        print(
            "Email failed: "
            "Gmail authentication failed."
        )


        print(
            "Check EMAIL_ADDRESS and "
            "EMAIL_PASSWORD."
        )


        print(
            "For Gmail, use a Gmail App Password "
            "instead of your normal Gmail password."
        )


        return False


    # ==========================================================
    # SMTP ERROR
    # ==========================================================

    except smtplib.SMTPException as e:

        print(
            f"Email failed: SMTP error: {e}"
        )

        return False


    # ==========================================================
    # GENERAL ERROR
    # ==========================================================

    except Exception as e:

        print(
            f"Email failed: {e}"
        )

        return False


    return True


# ==========================================================
# MODULE TEST
# ==========================================================

if __name__ == "__main__":

    print(
        "Emailer module loaded successfully."
    )

    print(
        "Email sending is available through "
        "send_email()."
    )